### ISSUE TITLE
Slow Loading Speeds

### ISSUE THREAD

**Issue by jawadyazbek313** [rgasch/filament-extended-starter-kit#6]

**Comment by rgasch** [comment]
Can you please be more specific (and if possible provide some benchmarks/timings)? 

Does this affect all the pages or just some? I tested things locally for me and it seemed fine, but if you can provide specifics I'll take a look.

**Comment by jawadyazbek313** [comment]
Hi there,
It slow for almost every page,
here are some captures showing the loading times
![Capture](https://user-images.githubusercontent.com/87113175/201487975-b009c911-ae91-4540-b769-030f5070ee7b.PNG)
![Capture1](https://user-images.githubusercontent.com/87113175/201487976-f28ba89e-7fba-4430-86ce-e1672c94c3d2.PNG)

**Comment by socbaysky** [comment]
maybe happen in local env in first time login, can you try deploy to production or setup production on your local device?

**Comment by jawadyazbek313** [comment]
I tried deploy using production its the same too many big files are loaded
in pages  even if they aint used

**Comment by rgasch** [comment]
You are correct in saying that lots of files are loaded but this is due to all the activated plugins.  However, there must be something weird/wrong on your end, because just using the base 1.0.3 install, I get loading times of < 1 second; I'm not sure what could be causing such a dramatic slowdown (assuming you have a reasonably 
![starterKitScreenshot](https://user-images.githubusercontent.com/343614/201607950-aebbf634-6b32-4d0e-9b4f-e4cecc9c51f5.jpg)
modern computer). 

In response to this, I've added caching directives to .htaccess and published this in a new release (v1.0.4); so please give that a try. This further improves speed; please see the attached screenshot from my local machine.

**Comment by jawadyazbek313** [comment]
Thanks, I'll check it out.

**Comment by gogo740618** [comment]
I also experienced slow loading speed on all pages -  removed tall-interactive package  and now speed is back within normal limits.

**Comment by rgasch** [comment]
Thank you for this observation, I added a comment to the README concerning this.
